export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const SET_CURRENT_PRODUCT = "SET_CURRENT_PRODUCT";
export const CLEAR_PRODUCT = "CLEAR_PRODUCT";
export const SET_QUANTITY = "SET_QUANTITY";
export const CREATE_OFFER = "CREATE_OFFER";
export const FETCH_OFFER_PRODUCTS = "FETCH_OFFER_PRODUCTS";
export const ADD_OFFER_ITEM = "ADD_OFFER_ITEM";
export const REMOVE_OFFER_ITEM = "REMOVE_OFFER_ITEM";
